### ISSUE TITLE
Error message lock/unlock

### ISSUE THREAD

**Issue by mipe79** [jockesyk/homeassistant-yale-doorman-via-smarthub#10]
I get the following errors when I try to lock/unlock my Yale doorman l2n:

```
object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/homeassistant-yale-doorman-via-smarthub/lock.py", line 61, in async_unlock
    await self.coordinator.async_set_updated_data(data)
TypeError: object NoneType can't be used in 'await' expression
```
Seems that it works to lock/unlock, but I get this error every time.

**Comment by mipe79** [comment]
This seems to be fixed in latest version.
