### ISSUE TITLE
adding entities for domain binary_sensor with platform yale_doorman_via_smarthub

### ISSUE THREAD

**Issue by Marmoulak** [jockesyk/homeassistant-yale-doorman-via-smarthub#29]
Hi
Would you please help with this errors?
 Home Assistant 2022.9.2 
Supervisor 2022.08.6 
Operating System 8.5 
Frontend 20220907.0 - latest 

    Error adding entities for domain binary_sensor with platform yale_doorman_via_smarthub
    Error while setting up yale_doorman_via_smarthub platform for binary_sensor

Traceback (most recent call last):
  File "/config/custom_components/yale_doorman_via_smarthub/binary_sensor.py", line 60, in icon
    door_status = int(self.coordinator.data["data"]["device_status"][self.idx]["minigw_lock_status"],16)
ValueError: invalid literal for int() with base 16: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/yale_doorman_via_smarthub/binary_sensor.py", line 63, in icon
    door_status = self.old_door_status
AttributeError: 'YaleDoormanViaSmarthubBinarySensor' object has no attribute 'old_door_status'

**Comment by jockesyk** [comment]
Thanks for the detailed error report. 
Version 0.0.8 (just released) should fix this.
